#!/usr/bin/env bash
set -euo pipefail
cd '/Users/tekitou/Desktop/gsim/loveca'
# Test A candidate selection PL!HS-bp5-018 DOLLCHESTRA
unset LLOCG_START_STAGE LLOCG_START_STAGE_L LLOCG_START_STAGE_C LLOCG_START_STAGE_R LLOCG_START_HAND LLOCG_START_HAND_SIZE LLOCG_START_SHUFFLE LLOCG_START_GREEN LLOCG_START_SUCCESS LLOCG_START_RESOLVE LLOCG_START_DECK_TOP LLOCG_START_DECK_EXACT LLOCG_START_DECK_EXACT_STRICT LLOCG_START_PHASE LLOCG_START_TURN LLOCG_START_ENERGY_ACTIVE LLOCG_START_ENERGY_WAIT LLOCG_START_OPPONENT_WAIT LLOCG_DEBUG_PRESET LLOCG_DEBUG_EFFECT_CARD LLOCG_START_DEBUG LLOCG_DEBUG_LIVE_IN_HAND LLOCG_DEBUG_MEMBER_IN_HAND
export LLOCG_DEBUG_PRESET='effect'
export LLOCG_DEBUG_EFFECT_CARD='PL!HS-cl1-002'
export LLOCG_START_PHASE='MAIN'
export LLOCG_START_TURN='1'
export LLOCG_START_DEBUG='1'
export LLOCG_START_HAND_SIZE='0'
export LLOCG_START_SHUFFLE='0'
export LLOCG_START_ENERGY_ACTIVE='40'
export LLOCG_START_ENERGY_WAIT='0'
export LLOCG_DEBUG_LIVE_IN_HAND='0'
export LLOCG_DEBUG_MEMBER_IN_HAND='0'
export LLOCG_START_DECK_EXACT_STRICT='1'
export LLOCG_START_DECK_EXACT='LL-bp1-001,LL-bp2-001,LL-bp3-001,LL-bp5-001,LL-bp5-002,PL!S-bp2-026,PL!SP-bp4-024'
export LLOCG_START_GREEN='PL!HS-bp5-018,LL-bp5-001'
python3 ./run_llocg_ui_web.py --host 127.0.0.1 --port 8799 --debug
