#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
llocg_fetch_all_card_images.py

Fetch LoveLive! OCG card images from the official site.

Strategy:
1) Build target card list from cards_min_tokv1.json (preferred) and compiled DB (union).
2) If <root>/official_image_manifest.json exists, try exact URLs from that manifest first.
3) For known prerelease products, optionally ingest exact preview-image URLs from
   <root>/official_preview_image_manifest.json into preview_card_images.
4) Before release, skip heuristic rarity URL probing by default.
5) For released cards still missing, fall back to heuristic folder / rarity inference.
6) For PR-family cards, heuristic rarity tries are restricted to PR / PR2 only.

Output layout:
  <root>/card_images/<FOLDER>/<CARDNO>-<RARITY>.png
  <root>/preview_card_images/<FOLDER>/<CARDNO>-<RARITY|PREVIEW>-PREVIEW*.jpg

Runtime contract:
  Resolve canonical card_images first, then preview_card_images as fallback.
"""
from __future__ import annotations

BUILD_TAG = "image_fetch_progress_logging_20260721a"

import argparse
import datetime as dt
import json
import random
import re
import time
import urllib.parse
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

try:
    import requests
except Exception:
    requests = None  # type: ignore

BASE_URL = "https://llofficial-cardgame.com/wordpress/wp-content/images/cardlist"

# Product release dates are generated by llocg_db_tool_v7.py during DB scrape.
# The image fetcher consumes <root>/product_release_registry.json so new products
# do not require source-code edits here.
PRODUCT_RELEASE_REGISTRY_FILENAME = "product_release_registry.json"

DEFAULT_RARITIES = [
    "SD", "CL", "N", "R", "R2", "L", "L2", "PR", "PR2", "P", "P2",
    "SEC", "SEC2", "SECL", "SRL", "DUO", "AR", "RM", "RE", "PE", "PE2", "SECE", "LLE",
]

KNOWN_FOLDERS = [
    "BP01", "BP02", "BP03", "BP04", "BP05", "BP06",
    "CLHS01",
    "PBHS", "PBSP", "PBLS", "PBLL", "PBnj",
    "PR",
    "SPSD01", "NSD01", "PLSD01", "LSSD01", "HSSD01", "SSD01",
]

PB_PREFIX_TO_FOLDER = {
    "PL!HS": "PBHS",
    "PL!SP": "PBSP",
    "PL!S":  "PBLS",
    "PL!LS": "PBLS",
    "PL!N":  "PBnj",
    "PL!":   "PBLL",
    "LL":    "PBLL",
}
SD_PREFIX_TO_FOLDER = {
    "PL!SP": "SPSD01",
    "PL!N":  "NSD01",
    "PL!HS": "HSSD01",
    "PL!LS": "LSSD01",
    "PL!S":  "SSD01",
    "PL!":   "PLSD01",
}
CL_PREFIX_TO_FOLDER = {
    # PL!HS-cl1-001 -> CLHS01/PL!HS-cl1-001-CL.png
    "PL!HS": "CLHS01",
}
RARITY_ALIAS = {
    "R+": "R2", "R＋": "R2",
    "L+": "L2", "L＋": "L2",
    "P+": "P2", "P＋": "P2",
    "PE+": "PE2", "PE＋": "PE2",
    "SEC+": "SEC2", "SEC＋": "SEC2",
    "PR+": "PR2", "PR＋": "PR2",
}

BP_RE = re.compile(r"(?:^|-)bp([1-9][0-9]*)(?:-|$)", re.IGNORECASE)
SD_RE = re.compile(r"(?:^|-)sd([0-9]+)(?:-|$)", re.IGNORECASE)
PB_RE = re.compile(r"(?:^|-)pb([0-9]+)(?:-|$)", re.IGNORECASE)
CL_RE = re.compile(r"(?:^|-)cl([0-9]+)(?:-|$)", re.IGNORECASE)


def _uniq_keep_order(xs: Sequence[str]) -> List[str]:
    seen = set()
    out: List[str] = []
    for x in xs:
        if x not in seen:
            out.append(x)
            seen.add(x)
    return out


def _read_text_lines(p: Path) -> List[str]:
    try:
        return [ln.strip() for ln in p.read_text(encoding="utf-8").splitlines()]
    except FileNotFoundError:
        return []


def _normalize_rarity_token(rarity: str) -> str:
    r = (rarity or "").strip().upper().replace("＋", "+")
    return RARITY_ALIAS.get(r, r)


def _sanitize_rarities(items: List[str]) -> List[str]:
    out: List[str] = []
    for x in (items or []):
        if x is None:
            continue
        s = str(x).strip().upper().replace("＋", "+")
        if ":" in s:
            s = s.split(":", 1)[1].strip()
        for p in re.split(r"[\s,]+", s):
            p = _normalize_rarity_token(p.strip())
            if not p:
                continue
            if re.fullmatch(r"[A-Z0-9\+]{1,8}", p):
                out.append(p)
    return _uniq_keep_order(out)


def load_rarities(root: Path, outdir: Path, extra_cli: Optional[str]) -> List[str]:
    if extra_cli:
        items = [x.strip() for x in extra_cli.split(",") if x.strip()]
        rarities = _sanitize_rarities(items)
        return rarities or list(DEFAULT_RARITIES)
    for cand in [outdir / "_RARITIES.txt", root / "_RARITIES.txt"]:
        lines = [ln for ln in _read_text_lines(cand) if ln and not ln.startswith("#")]
        if lines:
            items: List[str] = []
            for ln in lines:
                items.extend([x.strip() for x in ln.split(",") if x.strip()])
            rarities = _sanitize_rarities(items)
            if rarities:
                return rarities
    return list(DEFAULT_RARITIES)


def find_latest_compiled(root: Path) -> Optional[Path]:
    cand = list(root.glob("cards_compiled_v*.json")) + list(root.glob("cards_compiled_*.json"))
    return sorted(cand)[-1] if cand else None


def find_tokv1_json(root: Path) -> Optional[Path]:
    p = root / "cards_min_tokv1.json"
    return p if p.exists() else None


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _norm_cardno_for_filename(cardno: str) -> str:
    parts = (cardno or "").split("-")
    if not parts:
        return cardno
    last = parts[-1]
    if last.isdigit():
        parts[-1] = last.zfill(3)
    return "-".join(parts)


def _card_prefix(cardno: str) -> str:
    parts = (cardno or "").split("-")
    if not parts:
        return cardno
    head = parts[0]
    if head.startswith("PL!"):
        return head
    return head


def _product_family(cardno: str) -> str:
    c = (cardno or "").lower()
    if "-pr-" in c:
        return "pr"
    if "-sd" in c:
        return "sd"
    if "-pb" in c:
        return "pb"
    if "-bp" in c:
        return "bp"
    if "-cl" in c:
        return "cl"
    return "other"


def _record_cardnumber(obj: Dict[str, Any]) -> Optional[str]:
    for k in ("cardnumber", "cardNumber", "card_no", "cardno", "id", "number", "card_number"):
        v = obj.get(k)
        if isinstance(v, str) and v.strip():
            return v.strip()
    return None


def load_compiled_records(path: Optional[Path]) -> List[Dict[str, Any]]:
    if not path or not path.exists():
        return []
    compiled = load_json(path)
    out: List[Dict[str, Any]] = []

    def push(cardno: str, meta: Optional[Dict[str, Any]] = None) -> None:
        rec = dict(meta or {})
        rec["cardnumber"] = cardno
        out.append(rec)

    if isinstance(compiled, dict):
        if isinstance(compiled.get("cards"), list):
            for obj in compiled["cards"]:
                if isinstance(obj, dict):
                    cn = _record_cardnumber(obj)
                    if cn:
                        push(cn, obj)
                elif isinstance(obj, str) and obj.strip():
                    push(obj.strip())
        else:
            for k, v in compiled.items():
                if isinstance(v, dict):
                    cn = _record_cardnumber(v)
                    if cn:
                        push(cn, v)
                if isinstance(k, str) and "-" in k and re.search(r"(bp|sd|pr|pb)", k, re.I):
                    push(k)
    elif isinstance(compiled, list):
        for obj in compiled:
            if isinstance(obj, dict):
                cn = _record_cardnumber(obj)
                if cn:
                    push(cn, obj)
            elif isinstance(obj, str) and obj.strip():
                push(obj.strip())

    dedup: Dict[str, Dict[str, Any]] = {}
    for rec in out:
        cn = rec["cardnumber"].strip()
        if cn:
            dedup[cn] = rec
    return list(dedup.values())


def load_tokv1_records(path: Optional[Path]) -> List[Dict[str, Any]]:
    if not path or not path.exists():
        return []
    obj = load_json(path)
    cards = obj if isinstance(obj, list) else obj.get("cards", obj)
    out: List[Dict[str, Any]] = []
    if isinstance(cards, list):
        for rec in cards:
            if isinstance(rec, dict):
                cn = rec.get("cardnumber")
                if isinstance(cn, str) and cn.strip():
                    out.append(rec)
    return out


def load_target_records(root: Path, compiled_path: Optional[Path]) -> Tuple[List[Dict[str, Any]], Optional[Path], Optional[Path]]:
    tokv1_path = find_tokv1_json(root)
    tokv1_records = load_tokv1_records(tokv1_path)
    compiled_records = load_compiled_records(compiled_path)

    merged: Dict[str, Dict[str, Any]] = {}
    for rec in compiled_records:
        cn = _norm_cardno_for_filename(rec["cardnumber"].strip())
        rec = dict(rec)
        rec["cardnumber"] = cn
        merged[cn] = rec
    for rec in tokv1_records:
        cn = _norm_cardno_for_filename(rec["cardnumber"].strip())
        merged.setdefault(cn, {}).update(rec)
        merged[cn]["cardnumber"] = cn
    records = [merged[k] for k in sorted(merged.keys())]
    return records, tokv1_path, compiled_path


def build_url(folder: str, remote_filename: str) -> str:
    return f"{BASE_URL}/{folder}/{remote_filename}"


def folder_candidates_for_cardno(cardno: str) -> List[str]:
    c = cardno

    m = SD_RE.search(c)
    if m:
        pref = _card_prefix(c)
        folder = SD_PREFIX_TO_FOLDER.get(pref)
        sdnum = m.group(1)
        sdtag = f"SD{sdnum.zfill(2)}"
        cand: List[str] = []
        if folder:
            if folder.endswith("SD01"):
                cand.append(folder[:-2] + sdnum.zfill(2))
            else:
                cand.append(folder)
        cand.extend([f for f in KNOWN_FOLDERS if f.endswith(sdtag)])
        return _uniq_keep_order(cand)

    cm = CL_RE.search(c)
    if cm:
        pref = _card_prefix(c)
        folder = CL_PREFIX_TO_FOLDER.get(pref)
        clnum = cm.group(1).zfill(2)
        cand: List[str] = []
        if folder:
            cand.append(re.sub(r"\d{2}$", clnum, folder))
        cand.extend([f for f in KNOWN_FOLDERS if f.endswith(clnum) and f.startswith("CL")])
        return _uniq_keep_order([x for x in cand if x])

    if "-PR-" in c:
        return ["PR"]

    bm = BP_RE.search(c)
    if bm:
        return [f"BP{int(bm.group(1)):02d}"]

    pm = PB_RE.search(c)
    if pm:
        best = PB_PREFIX_TO_FOLDER.get(_card_prefix(c))
        pbnum = int(pm.group(1))
        # Product families with a known prefix should stay within that prefix's PB folder.
        # PB1 keeps the legacy folder name (e.g. PBSP), while PB2+ uses a two-digit
        # suffix used by the official image tree (e.g. PL!SP-pb2-xxx -> PBSP02).
        if best:
            folder = best if pbnum == 1 else f"{best}{pbnum:02d}"
            return [folder]
        return _uniq_keep_order([f for f in KNOWN_FOLDERS if f.startswith("PB")])

    return list(KNOWN_FOLDERS)


REPRINT_FOLDER_SCAN_RARITIES = {"L2", "SECL", "RM", "SRL"}


def reprint_folder_candidates(
    base_folders: Sequence[str],
    product_release_dates: Dict[str, str],
) -> List[str]:
    registry_folders = [
        str(code).strip()
        for code in product_release_dates.keys()
        if re.fullmatch(
            r"(?:BP|PB|CL|[A-Z]*SD)\w*",
            str(code).strip(),
            re.IGNORECASE,
        )
    ]
    return _uniq_keep_order(
        [
            folder
            for folder in list(base_folders) + KNOWN_FOLDERS + registry_folders
            if folder
        ]
    )


def _manifest_reprint_rarities(entries: Sequence[Dict[str, Any]]) -> List[str]:
    return _uniq_keep_order(
        [
            rarity
            for rarity in _sanitize_rarities(
                [str(e.get("rarity_norm", "") or "") for e in entries if isinstance(e, dict)]
            )
            if rarity in REPRINT_FOLDER_SCAN_RARITIES
        ]
    )


def family_rarities(cardno: str, global_rarities: Sequence[str], manifest_entries: Optional[List[Dict[str, Any]]] = None) -> List[str]:
    manifest_rs: List[str] = []
    if manifest_entries:
        manifest_rs = [e.get("rarity_norm", "") for e in manifest_entries if isinstance(e, dict)]
        manifest_rs = _sanitize_rarities(manifest_rs)
    fam = _product_family(cardno)
    if fam == "sd":
        fam_order = ["SD"]
    elif fam == "pr":
        # PR family is intentionally narrow.
        # In current local validation, PR cards are covered by PR / PR2 only;
        # trying broader rarity families just generates large numbers of 404s.
        fam_order = ["PR", "PR2"]
    elif fam == "cl":
        fam_order = ["CL"]
    elif fam in {"bp", "pb"}:
        fam_order = ["N", "R", "R2", "L", "L2", "RM", "AR", "SEC", "SEC2", "SECL", "SRL", "DUO", "RE", "PE", "PE2", "SECE", "LLE", "P", "P2", "PR", "PR2"]
    else:
        fam_order = []
    if fam == "pr":
        combined = manifest_rs + fam_order
    else:
        combined = manifest_rs + fam_order + list(global_rarities)
    return _uniq_keep_order(_sanitize_rarities(combined))


def _rarity_mid_token(rarity: str) -> str:
    r = _normalize_rarity_token(rarity)
    if r.endswith("2") and len(r) >= 2:
        return r[:-1]
    return r


def remote_filename_variants(folder: str, cardno: str, rarity: str) -> List[str]:
    folder_u = (folder or "").strip().upper()
    r = _normalize_rarity_token(rarity)
    out: List[str] = [f"{cardno}-{r}.png"]

    # Official PR image filename exception:
    # PL!N-PR-022-PR is published with a SAMPLE prefix immediately before
    # the card number in the raw image filename. Keep this card-scoped so
    # ordinary PR URL probing remains unchanged.
    if folder_u == "PR" and cardno.upper() == "PL!N-PR-022":
        out.append(f"SAMPLE{cardno}-{r}.png")

    if folder_u == "PR":
        cn2 = cardno
        cn2_low = cn2.lower()
        if "-pr-" in cn2_low:
            parts = re.split("(?i)-pr-", cn2)
            if len(parts) >= 2:
                cn_drop = "-".join([parts[0]] + parts[1:])
                out.append(f"{cn_drop}-{r}.png")

    cn_low = cardno.lower()
    if folder_u == "BP03" and "-bp3-" in cn_low:
        idx = cn_low.find("-bp3-")
        prefix = cardno[:idx]
        set_tok = cardno[idx + 1: idx + 4]
        rest = cardno[idx + 5:]
        parts = rest.split("-")
        num = parts[-1]
        mids = [r, _rarity_mid_token(r)]
        for mid in _uniq_keep_order([m for m in mids if m]):
            out.append(f"{prefix}-{set_tok}-{mid}-{num}-{r}.png")

    return _uniq_keep_order(out)


def load_official_manifest(root: Path) -> Dict[str, List[Dict[str, Any]]]:
    path = root / "official_image_manifest.json"
    if not path.exists():
        return {}
    try:
        obj = load_json(path)
    except Exception:
        return {}
    cards = obj.get("cards", {}) if isinstance(obj, dict) else {}
    out: Dict[str, List[Dict[str, Any]]] = {}
    if isinstance(cards, dict):
        for cn, entries in cards.items():
            if isinstance(cn, str) and isinstance(entries, list):
                out[_norm_cardno_for_filename(cn)] = [e for e in entries if isinstance(e, dict)]
    return out


def load_preview_manifest(path: Path) -> Dict[str, List[Dict[str, Any]]]:
    if not path.exists():
        return {}
    try:
        obj = load_json(path)
    except Exception:
        return {}
    cards = obj.get("cards", {}) if isinstance(obj, dict) else {}
    out: Dict[str, List[Dict[str, Any]]] = {}
    if isinstance(cards, dict):
        for cn, entries in cards.items():
            if isinstance(cn, str) and isinstance(entries, list):
                out[_norm_cardno_for_filename(cn)] = [e for e in entries if isinstance(e, dict)]
    return out


def _product_code_for_cardno(cardno: str) -> Optional[str]:
    c = cardno or ""

    bm = BP_RE.search(c)
    if bm:
        return f"BP{int(bm.group(1)):02d}"

    pm = PB_RE.search(c)
    if pm:
        pref = _card_prefix(c)
        base = PB_PREFIX_TO_FOLDER.get(pref)
        if base:
            pbnum = int(pm.group(1))
            return base if pbnum == 1 else f"{base}{pbnum:02d}"
        return None

    sm = SD_RE.search(c)
    if sm:
        pref = _card_prefix(c)
        base = SD_PREFIX_TO_FOLDER.get(pref)
        if base:
            sdnum = int(sm.group(1))
            if base.endswith("SD01"):
                return base[:-2] + f"{sdnum:02d}"
            return base
        return None

    cm = CL_RE.search(c)
    if cm:
        pref = _card_prefix(c)
        base = CL_PREFIX_TO_FOLDER.get(pref)
        if base:
            return re.sub(r"\d{2}$", f"{int(cm.group(1)):02d}", base)
        return None

    return None


def load_product_release_dates(path: Path) -> Dict[str, str]:
    if not path.exists():
        return {}
    try:
        obj = load_json(path)
    except Exception as exc:
        raise SystemExit(f"[ERROR] failed to load product release registry: {path}: {exc}") from exc

    products = obj.get("products", {}) if isinstance(obj, dict) else {}
    if not isinstance(products, dict):
        raise SystemExit(f"[ERROR] invalid product release registry: {path}")

    out: Dict[str, str] = {}
    for code, raw in products.items():
        code_norm = str(code or "").strip().upper()
        if not code_norm:
            continue
        if isinstance(raw, dict):
            release_date = str(raw.get("release_date", "") or "").strip()
        else:
            release_date = str(raw or "").strip()
        if not release_date:
            continue
        _parse_iso_date(release_date, label=f"release date for {code_norm}")
        out[code_norm] = release_date
    return out


def _parse_iso_date(value: str, *, label: str) -> dt.date:
    try:
        return dt.date.fromisoformat(str(value).strip())
    except Exception as e:
        raise SystemExit(f"[ERROR] invalid {label}: {value!r}; expected YYYY-MM-DD") from e


def prerelease_info(
    cardno: str,
    as_of: dt.date,
    product_release_dates: Dict[str, str],
) -> Optional[Tuple[str, dt.date]]:
    product = _product_code_for_cardno(cardno)
    if not product:
        return None
    raw = product_release_dates.get(product)
    if not raw:
        return None
    release_date = _parse_iso_date(raw, label=f"release date for {product}")
    if as_of < release_date:
        return product, release_date
    return None


def _preview_suffix_from_url(url: str) -> str:
    parsed = urllib.parse.urlparse(url or "")
    query = urllib.parse.parse_qs(parsed.query)
    fmt = str((query.get("format") or [""])[0]).lower().strip()
    if fmt in {"png", "jpg", "jpeg", "webp"}:
        return ".jpg" if fmt == "jpeg" else f".{fmt}"
    suffix = Path(urllib.parse.unquote(parsed.path)).suffix.lower()
    if suffix in {".png", ".jpg", ".jpeg", ".webp"}:
        return ".jpg" if suffix == ".jpeg" else suffix
    return ".jpg"


@dataclass
class TryResult:
    ok: bool
    status: str
    url: str
    path: str
    folder: str
    cardno: str
    rarity: str
    mode: str
    bytes: int = 0


def _ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)


def _urllib_get(url: str, headers: Dict[str, str], timeout: float, insecure: bool) -> Tuple[int, bytes]:
    import ssl
    from urllib.request import Request, urlopen
    ctx = None
    if insecure:
        ctx = ssl._create_unverified_context()
    req = Request(url, headers=headers)
    with urlopen(req, timeout=timeout, context=ctx) as r:
        data = r.read()
        return int(getattr(r, "status", 200) or 200), data


def _http_get(sess: Optional["requests.Session"], url: str, headers: Dict[str, str], timeout: float, verify: bool) -> Tuple[int, bytes]:
    if sess is None:
        return _urllib_get(url, headers=headers, timeout=timeout, insecure=not verify)
    resp = sess.get(url, timeout=timeout, headers=headers, verify=verify)
    return resp.status_code, resp.content


def _download_url(
    sess: Optional["requests.Session"],
    url: str,
    out_path: Path,
    timeout: float,
    allow_insecure_fallback: bool,
    state: Dict[str, Any],
) -> Tuple[bool, str, int]:
    verify = not bool(state.get("insecure", False))
    try:
        status_code, content = _http_get(sess, url, state["headers"], timeout=timeout, verify=verify)
    except Exception as e:
        msg = f"{type(e).__name__}: {e}"
        if allow_insecure_fallback and ("CERTIFICATE_VERIFY_FAILED" in msg or "SSLError" in msg or "ssl" in msg.lower()) and not state.get("insecure_used", False):
            state["insecure_used"] = True
            state["insecure"] = True
            try:
                status_code, content = _http_get(sess, url, state["headers"], timeout=timeout, verify=False)
            except Exception as e2:
                return False, f"EXC {type(e2).__name__}", 0
        else:
            return False, f"EXC {type(e).__name__}", 0

    if status_code != 200 or not content:
        return False, f"HTTP {status_code}", 0

    _ensure_dir(out_path.parent)
    out_path.write_bytes(content)
    return True, "OK", len(content)


def try_manifest_entry(
    sess: Optional["requests.Session"],
    cardno: str,
    entry: Dict[str, Any],
    outdir: Path,
    skip_existing: bool,
    timeout: float,
    allow_insecure_fallback: bool,
    state: Dict[str, Any],
) -> TryResult:
    folder = str(entry.get("folder", "") or "")
    rarity = _normalize_rarity_token(str(entry.get("rarity_norm", "") or ""))
    remote_filename = str(entry.get("remote_filename", "") or "")
    exact_url = str(entry.get("exact_url", "") or "")
    if not folder or not rarity:
        return TryResult(False, "BAD_ENTRY", "", "", folder, cardno, rarity, "manifest", 0)

    out_path = outdir / folder / f"{cardno}-{rarity}.png"
    if skip_existing and out_path.exists() and out_path.stat().st_size > 0:
        return TryResult(True, "SKIP_EXISTS", exact_url, str(out_path), folder, cardno, rarity, "manifest", 0)

    urls = []
    if exact_url:
        urls.append(exact_url)
    if remote_filename:
        built = build_url(folder, remote_filename)
        if built not in urls:
            urls.append(built)

    last_status = "NO_TRY"
    last_url = ""
    for url in urls:
        last_url = url
        ok, status, nbytes = _download_url(sess, url, out_path, timeout, allow_insecure_fallback, state)
        if ok:
            return TryResult(True, status, url, str(out_path), folder, cardno, rarity, "manifest", nbytes)
        last_status = status

    return TryResult(False, last_status, last_url, str(out_path), folder, cardno, rarity, "manifest", 0)


def try_preview_entry(
    sess: Optional["requests.Session"],
    cardno: str,
    entry: Dict[str, Any],
    preview_outdir: Path,
    entry_index: int,
    skip_existing: bool,
    timeout: float,
    allow_insecure_fallback: bool,
    state: Dict[str, Any],
) -> TryResult:
    folder = str(entry.get("folder", "") or "").strip() or (_product_code_for_cardno(cardno) or "PREVIEW")
    rarity = _normalize_rarity_token(str(entry.get("rarity_norm", "") or entry.get("rarity", "") or ""))
    url = str(entry.get("image_url", "") or entry.get("exact_url", "") or entry.get("url", "") or "").strip()
    if not url:
        return TryResult(False, "BAD_PREVIEW_ENTRY", "", "", folder, cardno, rarity, "preview_manifest", 0)

    suffix = _preview_suffix_from_url(url)
    serial = f"-{entry_index:02d}" if entry_index > 1 else ""
    stem = f"{cardno}-{rarity}-PREVIEW" if rarity else f"{cardno}-PREVIEW"
    out_path = preview_outdir / folder / f"{stem}{serial}{suffix}"
    if skip_existing and out_path.exists() and out_path.stat().st_size > 0:
        return TryResult(True, "SKIP_EXISTS", url, str(out_path), folder, cardno, rarity, "preview_manifest", 0)

    ok, status, nbytes = _download_url(sess, url, out_path, timeout, allow_insecure_fallback, state)
    if ok:
        return TryResult(True, status, url, str(out_path), folder, cardno, rarity, "preview_manifest", nbytes)
    return TryResult(False, status, url, str(out_path), folder, cardno, rarity, "preview_manifest", 0)


def try_heuristic(
    sess: Optional["requests.Session"],
    cardno: str,
    folder: str,
    rarity: str,
    outdir: Path,
    skip_existing: bool,
    timeout: float,
    allow_insecure_fallback: bool,
    state: Dict[str, Any],
) -> TryResult:
    rarity = _normalize_rarity_token(rarity)
    out_path = outdir / folder / f"{cardno}-{rarity}.png"
    if skip_existing and out_path.exists() and out_path.stat().st_size > 0:
        return TryResult(True, "SKIP_EXISTS", "", str(out_path), folder, cardno, rarity, "heuristic", 0)

    last_status = "NO_TRY"
    last_url = ""
    for remote_filename in remote_filename_variants(folder, cardno, rarity):
        url = build_url(folder, remote_filename)
        last_url = url
        ok, status, nbytes = _download_url(sess, url, out_path, timeout, allow_insecure_fallback, state)
        if ok:
            return TryResult(True, status, url, str(out_path), folder, cardno, rarity, "heuristic", nbytes)
        last_status = status
    return TryResult(False, last_status, last_url, str(out_path), folder, cardno, rarity, "heuristic", 0)



def load_cardnumber_filter(path: Optional[Path]) -> Optional[set[str]]:
    if path is None:
        return None
    if not path.exists():
        raise SystemExit(f"[ERR] cardnumber filter file not found: {path}")
    out: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        value = raw.strip()
        if not value or value.startswith("#"):
            continue
        out.add(_norm_cardno_for_filename(value))
    return out


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=Path, required=True, help="Project root (contains cards_min_tokv1.json / cards_compiled_*.json)")
    ap.add_argument("--compiled", type=Path, default=None, help="Optional compiled JSON path")
    ap.add_argument(
        "--cardnumber-file",
        type=Path,
        default=None,
        help="Optional newline-separated cardnumber allowlist for incremental image fetching",
    )
    ap.add_argument("--outdir", type=Path, default=None, help="Output dir (default: <root>/card_images)")
    ap.add_argument("--preview-outdir", type=Path, default=None, help="Preview image dir (default: <root>/preview_card_images)")
    ap.add_argument("--preview-manifest", type=Path, default=None, help="Optional preview manifest JSON (default: <root>/official_preview_image_manifest.json)")
    ap.add_argument("--product-registry", type=Path, default=None, help="Product release registry JSON (default: <root>/product_release_registry.json)")
    ap.add_argument("--skip-prerelease", action="store_true", help="Before release, use exact manifest/preview manifest only and skip heuristic URL probing (default ON)")
    ap.add_argument("--no-skip-prerelease", dest="skip_prerelease", action="store_false", help="Allow legacy heuristic URL probing before release")
    ap.set_defaults(skip_prerelease=True)
    ap.add_argument("--as-of", type=str, default="", help="Date for prerelease judgment, YYYY-MM-DD (default: local today)")
    ap.add_argument("--rarities", type=str, default=None, help="Comma-separated rarities to try (overrides _RARITIES.txt)")
    ap.add_argument("--all-rarities", action="store_true", help="Try to fetch all rarities for each card (default ON)")
    ap.add_argument("--no-all-rarities", dest="all_rarities", action="store_false", help="Stop after first success per card+folder")
    ap.set_defaults(all_rarities=True)
    ap.add_argument("--skip-existing", action="store_true", help="Skip already-downloaded files (default ON)")
    ap.add_argument("--no-skip-existing", dest="skip_existing", action="store_false")
    ap.set_defaults(skip_existing=True)
    ap.add_argument("--timeout", type=float, default=10.0)
    ap.add_argument("--sleep", type=float, default=0.02)
    ap.add_argument("--jitter", type=float, default=0.03)
    ap.add_argument("--max-warn-total", type=int, default=40)
    ap.add_argument("--max-warn-per-card", type=int, default=2)
    ap.add_argument("--progress-every", type=int, default=10, help="Print image fetch progress every N cards")
    ap.add_argument("--user-agent", type=str, default="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36")
    ap.add_argument("--quiet", action="store_true")
    ap.add_argument("--insecure", action="store_true")
    ap.add_argument("--no-insecure-fallback", action="store_true")
    args = ap.parse_args(argv)

    def _log(*a, **k):
        if not args.quiet:
            k.setdefault("flush", True)
            print(*a, **k)

    root = args.root.resolve()
    compiled_path = args.compiled.resolve() if args.compiled else find_latest_compiled(root)
    outdir = args.outdir.resolve() if args.outdir else (root / "card_images")
    preview_outdir = args.preview_outdir.resolve() if args.preview_outdir else (root / "preview_card_images")
    preview_manifest_path = args.preview_manifest.resolve() if args.preview_manifest else (root / "official_preview_image_manifest.json")
    product_registry_path = args.product_registry.resolve() if args.product_registry else (root / PRODUCT_RELEASE_REGISTRY_FILENAME)
    product_release_dates = load_product_release_dates(product_registry_path)
    as_of = _parse_iso_date(args.as_of, label="--as-of") if args.as_of else dt.date.today()
    outdir.mkdir(parents=True, exist_ok=True)
    preview_outdir.mkdir(parents=True, exist_ok=True)

    global_rarities = load_rarities(root, outdir, args.rarities)
    global_rarities = _uniq_keep_order(_sanitize_rarities(global_rarities)) or list(DEFAULT_RARITIES)

    target_records, tokv1_path, compiled_path = load_target_records(root, compiled_path)
    cardnumber_filter = load_cardnumber_filter(
        args.cardnumber_file.resolve() if args.cardnumber_file else None
    )
    if cardnumber_filter is not None:
        before_count = len(target_records)
        target_records = [
            rec
            for rec in target_records
            if _norm_cardno_for_filename(str(rec.get("cardnumber", "") or "").strip())
            in cardnumber_filter
        ]
        _log(
            f"[TARGET-FILTER] requested={len(cardnumber_filter)} "
            f"matched={len(target_records)} db_total={before_count}"
        )
    if not target_records:
        if cardnumber_filter is not None:
            print("[DONE] no matching cardnumbers for incremental image fetch", flush=True)
            return 0
        print("[ERR] No card numbers found in tokv1/compiled DB.", flush=True)
        print("      tokv1   :", tokv1_path, flush=True)
        print("      compiled:", compiled_path, flush=True)
        return 2

    manifest = load_official_manifest(root)
    preview_manifest = load_preview_manifest(preview_manifest_path)
    progress_every = max(1, int(args.progress_every or 1))
    _log(
        "[IMAGE-FETCH-START] "
        f"targets={len(target_records)} outdir={outdir} preview={preview_outdir} "
        f"manifest={bool(manifest)} preview_manifest={bool(preview_manifest)} "
        f"progress_every={progress_every}"
    )

    sess = requests.Session() if requests is not None else None
    state: Dict[str, Any] = {
        "headers": {"User-Agent": args.user_agent},
        "insecure": bool(args.insecure),
        "insecure_used": False,
    }
    allow_fallback = not args.no_insecure_fallback

    results: List[TryResult] = []
    ok_files = 0
    skip_files = 0
    fail_attempts = 0
    manifest_success = 0
    heuristic_success = 0
    preview_success = 0
    preview_skip_files = 0
    skipped_prerelease = 0
    manifest_cards = 0

    warn_total = 0
    warn_by_card: Dict[str, int] = {}

    for i, rec in enumerate(target_records, 1):
        cardno = _norm_cardno_for_filename(rec["cardnumber"].strip())
        manifest_entries = manifest.get(cardno, [])
        preview_entries = preview_manifest.get(cardno, [])
        pre = prerelease_info(cardno, as_of, product_release_dates)
        if manifest_entries:
            manifest_cards += 1

        per_card_results: List[TryResult] = []
        card_had_success = False
        successful_rarities: set[str] = set()
        manifest_reprint_rarities = _manifest_reprint_rarities(manifest_entries)

        # 1) exact manifest URLs
        if manifest_entries:
            for entry_index, entry in enumerate(manifest_entries):
                entry_rarity = _normalize_rarity_token(str(entry.get("rarity_norm", "") or ""))
                tr = try_manifest_entry(
                    sess=sess,
                    cardno=cardno,
                    entry=entry,
                    outdir=outdir,
                    skip_existing=args.skip_existing,
                    timeout=args.timeout,
                    allow_insecure_fallback=allow_fallback,
                    state=state,
                )
                per_card_results.append(tr)
                if tr.ok:
                    card_had_success = True
                    if tr.rarity:
                        successful_rarities.add(_normalize_rarity_token(tr.rarity))
                    if tr.status == "SKIP_EXISTS":
                        skip_files += 1
                    else:
                        ok_files += 1
                    manifest_success += 1
                    remaining_reprints = {
                        rarity
                        for rarity in manifest_reprint_rarities
                        if rarity not in successful_rarities
                    }
                    current_is_reprint = entry_rarity in REPRINT_FOLDER_SCAN_RARITIES
                    if (
                        (not args.all_rarities)
                        and tr.status != "SKIP_EXISTS"
                        and not current_is_reprint
                        and not remaining_reprints
                    ):
                        break
                else:
                    fail_attempts += 1

                if tr.status != "SKIP_EXISTS":
                    time.sleep(args.sleep + random.random() * args.jitter)

        # 2) prerelease preview manifest. This is intentionally separate from
        # card_images so X/social preview assets never become canonical raw images.
        if (not card_had_success) and pre and preview_entries:
            for preview_index, entry in enumerate(preview_entries, 1):
                tr = try_preview_entry(
                    sess=sess,
                    cardno=cardno,
                    entry=entry,
                    preview_outdir=preview_outdir,
                    entry_index=preview_index,
                    skip_existing=args.skip_existing,
                    timeout=args.timeout,
                    allow_insecure_fallback=allow_fallback,
                    state=state,
                )
                per_card_results.append(tr)
                if tr.ok:
                    card_had_success = True
                    if tr.status == "SKIP_EXISTS":
                        preview_skip_files += 1
                    else:
                        preview_success += 1
                    if not args.all_rarities:
                        break
                else:
                    fail_attempts += 1
                if tr.status != "SKIP_EXISTS":
                    time.sleep(args.sleep + random.random() * args.jitter)

        # 3) before release, do not probe guessed rarity URLs when exact official
        # image/preview metadata could not provide an image.
        skip_heuristic_for_prerelease = bool(pre and args.skip_prerelease and not card_had_success)
        if skip_heuristic_for_prerelease:
            product, release_date = pre
            folders = folder_candidates_for_cardno(cardno)
            folder = folders[0] if folders else product
            per_card_results.append(TryResult(
                False,
                "SKIP_PRE_RELEASE",
                "",
                "",
                folder,
                cardno,
                "",
                "prerelease",
                0,
            ))
            skipped_prerelease += 1
            _log(f"[SKIP_PRE_RELEASE] {cardno} product={product} release={release_date.isoformat()} no usable exact/preview image")

        missing_manifest_reprint_rarities = [
            rarity
            for rarity in manifest_reprint_rarities
            if rarity not in successful_rarities
        ]

        # 4) heuristic fallback if manifest/preview is absent or unsuccessful.
        # Reprint/parallel rarities are different: a normal rarity image can
        # succeed while the reprint image lives under a folder that does not
        # match the card number's expansion token.  In that case, keep probing
        # only the still-missing reprint rarities across known product folders.
        probe_missing_reprints = bool(card_had_success and missing_manifest_reprint_rarities)
        if ((not card_had_success) or missing_manifest_reprint_rarities) and (not skip_heuristic_for_prerelease):
            folders = []
            if manifest_entries:
                folders.extend([str(e.get("folder", "") or "") for e in manifest_entries if str(e.get("folder", "") or "")])
            folders.extend(folder_candidates_for_cardno(cardno))
            folders = _uniq_keep_order([f for f in folders if f])

            if card_had_success and missing_manifest_reprint_rarities:
                rarities = missing_manifest_reprint_rarities
            else:
                rarities = family_rarities(cardno, global_rarities, manifest_entries=manifest_entries)
            chosen_folder = None

            normal_folders = list(folders)
            reprint_folders = reprint_folder_candidates(
                folders,
                product_release_dates,
            )
            folder_results_map: Dict[str, List[TryResult]] = {}
            successful_folder = ""

            for rarity in rarities:
                rarity_norm = _normalize_rarity_token(rarity)
                rarity_had_success = False
                rarity_folders = (
                    reprint_folders
                    if rarity_norm in REPRINT_FOLDER_SCAN_RARITIES
                    else normal_folders
                )

                for folder in rarity_folders:
                    tr = try_heuristic(
                        sess=sess,
                        cardno=cardno,
                        folder=folder,
                        rarity=rarity_norm,
                        outdir=outdir,
                        skip_existing=args.skip_existing,
                        timeout=args.timeout,
                        allow_insecure_fallback=allow_fallback,
                        state=state,
                    )
                    folder_results_map.setdefault(folder, []).append(tr)
                    per_card_results.append(tr)

                    if tr.ok:
                        card_had_success = True
                        rarity_had_success = True
                        if tr.rarity:
                            successful_rarities.add(_normalize_rarity_token(tr.rarity))
                        successful_folder = successful_folder or folder
                        chosen_folder = chosen_folder or folder
                        if tr.status == "SKIP_EXISTS":
                            skip_files += 1
                        else:
                            ok_files += 1
                        heuristic_success += 1
                        if not args.all_rarities:
                            break
                    else:
                        fail_attempts += 1

                    if tr.status != "SKIP_EXISTS":
                        time.sleep(args.sleep + random.random() * args.jitter)

                if probe_missing_reprints:
                    continue
                if rarity_had_success and not args.all_rarities:
                    break

            if not card_had_success:
                for folder in normal_folders:
                    folder_results = folder_results_map.get(folder, [])
                    warn_by_card.setdefault(cardno, 0)
                    if (
                        warn_total < args.max_warn_total
                        and warn_by_card[cardno] < args.max_warn_per_card
                    ):
                        ex = folder_results[0].url if folder_results else ""
                        _log(
                            f"[WARN] {cardno}: no images under folder={folder} "
                            f"(example {ex})"
                        )
                        warn_total += 1
                        warn_by_card[cardno] += 1

        results.extend(per_card_results)

        if i == 1 or i == len(target_records) or i % progress_every == 0:
            _log(
                "[IMAGE-FETCH-PROGRESS] "
                f"{i}/{len(target_records)} card={cardno} "
                f"ok_files={ok_files} skipped={skip_files} preview={preview_success} "
                f"prerelease_skip={skipped_prerelease} fail_attempts={fail_attempts} "
                f"manifest_cards={manifest_cards}"
            )

    report = {
        "root": str(root),
        "tokv1": str(tokv1_path) if tokv1_path else "",
        "compiled": str(compiled_path) if compiled_path else "",
        "cardnumber_filter": str(args.cardnumber_file.resolve()) if args.cardnumber_file else "",
        "cardnumber_filter_count": len(cardnumber_filter) if cardnumber_filter is not None else None,
        "outdir": str(outdir),
        "preview_outdir": str(preview_outdir),
        "manifest_present": bool(manifest),
        "preview_manifest": str(preview_manifest_path),
        "preview_manifest_present": bool(preview_manifest),
        "as_of": as_of.isoformat(),
        "skip_prerelease": bool(args.skip_prerelease),
        "product_registry": str(product_registry_path),
        "product_registry_present": product_registry_path.exists(),
        "product_release_dates": product_release_dates,
        "rarities": global_rarities,
        "counts": {
            "cards_total": len(target_records),
            "cards_with_manifest": manifest_cards,
            "ok_files": ok_files,
            "skipped": skip_files,
            "fail_attempts": fail_attempts,
            "manifest_successes": manifest_success,
            "preview_successes": preview_success,
            "preview_skipped_existing": preview_skip_files,
            "skipped_prerelease": skipped_prerelease,
            "heuristic_successes": heuristic_success,
        },
        "notes": {
            "insecure_mode_used": bool(state.get("insecure_used", False) or state.get("insecure", False)),
            "strategy": "canonical manifest exact URL first; prerelease preview manifest second; heuristic fallback blocked before known release dates by default",
            "preview_runtime_contract": "simulator should resolve card_images first, then preview_card_images as fallback",
        },
        "results": [tr.__dict__ for tr in results],
    }
    rep_path = outdir / "_download_report.json"
    rep_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    fail_lines: List[str] = []
    for tr in results:
        if (not tr.ok) and tr.status not in {"SKIP_EXISTS", "SKIP_PRE_RELEASE"}:
            fail_lines.append(f"{tr.cardno}\t{tr.folder}\t{tr.rarity}\t{tr.mode}\t{tr.status}\t{tr.url}")
    fail_log = outdir / "_failures.log"
    fail_log.write_text("\n".join(fail_lines) + ("\n" if fail_lines else ""), encoding="utf-8")

    print("[DONE]", flush=True)
    print("tokv1    :", tokv1_path, flush=True)
    print("compiled :", compiled_path, flush=True)
    print("outdir   :", outdir, flush=True)
    print("preview  :", preview_outdir, flush=True)
    print("manifest :", bool(manifest), flush=True)
    print("preview_manifest:", bool(preview_manifest), preview_manifest_path, flush=True)
    print("product_registry:", product_registry_path.exists(), product_registry_path, flush=True)
    print("release_products:", len(product_release_dates), flush=True)
    print("as_of    :", as_of.isoformat(), flush=True)
    print("rarities :", ", ".join(global_rarities), flush=True)
    print("ok_files :", ok_files, flush=True)
    print("skipped  :", skip_files, flush=True)
    print("preview_ok:", preview_success, flush=True)
    print("preview_skipped:", preview_skip_files, flush=True)
    print("prerelease_skipped:", skipped_prerelease, flush=True)
    print("failed   :", len(fail_lines), flush=True)
    print("report   :", rep_path, flush=True)
    print("fail_log :", fail_log, flush=True)

    if ok_files == 0 and skip_files == 0 and preview_success == 0 and preview_skip_files == 0 and skipped_prerelease == 0:
        print("[ERR] No files were downloaded, skipped, previewed, or safely skipped as prerelease. This usually means target extraction failed or all URLs are unreachable.", flush=True)
        return 3

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
