#!/usr/bin/env bash
set -euo pipefail
cd /Users/tekitou/Desktop/gsim/loveca
unset LLOCG_START_STAGE LLOCG_START_STAGE_L LLOCG_START_STAGE_C LLOCG_START_STAGE_R   LLOCG_START_HAND LLOCG_START_HAND_SIZE LLOCG_START_SHUFFLE   LLOCG_START_GREEN LLOCG_START_SUCCESS LLOCG_START_RESOLVE   LLOCG_START_DECK_TOP LLOCG_START_DECK_EXACT   LLOCG_START_PHASE LLOCG_START_TURN   LLOCG_START_ENERGY_ACTIVE LLOCG_START_ENERGY_WAIT   LLOCG_DEBUG_PRESET LLOCG_DEBUG_EFFECT_CARD LLOCG_START_DEBUG   LLOCG_DEBUG_LIVE_IN_HAND LLOCG_DEBUG_MEMBER_IN_HAND
export LLOCG_DEBUG_PRESET=effect
export LLOCG_START_PHASE=MAIN
export LLOCG_START_TURN=1
export LLOCG_START_STAGE_C='PL!SP-bp1-003'
export LLOCG_START_HAND='PL!N-bp3-009,PL!N-bp3-009,PL!N-bp1-029'
export LLOCG_START_HAND_SIZE=0
export LLOCG_START_DECK_TOP='PL!N-bp4-030,PL!N-bp3-032'
python3 ./run_llocg_ui_web.py --host 127.0.0.1 --port 8810 --debug
