#!/usr/bin/env bash
set -euo pipefail
cd '/Users/tekitou/Desktop/gsim/loveca'
# Group alias deck test for PL!HS-bp2-020, control=True
unset LLOCG_START_STAGE LLOCG_START_STAGE_L LLOCG_START_STAGE_C LLOCG_START_STAGE_R LLOCG_START_HAND LLOCG_START_HAND_SIZE LLOCG_START_SHUFFLE LLOCG_START_GREEN LLOCG_START_SUCCESS LLOCG_START_RESOLVE LLOCG_START_DECK_TOP LLOCG_START_DECK_EXACT LLOCG_START_DECK_EXACT_STRICT LLOCG_START_PHASE LLOCG_START_TURN LLOCG_START_ENERGY_ACTIVE LLOCG_START_ENERGY_WAIT LLOCG_START_OPPONENT_WAIT LLOCG_DEBUG_PRESET LLOCG_DEBUG_EFFECT_CARD LLOCG_START_DEBUG LLOCG_DEBUG_LIVE_IN_HAND LLOCG_DEBUG_MEMBER_IN_HAND
export LLOCG_DEBUG_PRESET='effect'
export LLOCG_DEBUG_EFFECT_CARD='PL!HS-bp1-009'
export LLOCG_START_PHASE='MAIN'
export LLOCG_START_TURN='1'
export LLOCG_START_DEBUG='1'
export LLOCG_START_HAND='PL!HS-bp1-009,LL-bp1-001'
export LLOCG_START_HAND_SIZE='0'
export LLOCG_START_STAGE_C='PL!N-bp5-001'
export LLOCG_START_ENERGY_ACTIVE='40'
export LLOCG_START_SHUFFLE='0'
export LLOCG_START_DECK_EXACT_STRICT='1'
export LLOCG_START_DECK_EXACT='LL-bp5-001,LL-bp1-001,LL-bp5-001,LL-bp2-001,LL-bp3-001,LL-bp5-002'
python3 ./run_llocg_ui_web.py --host 127.0.0.1 --port 8799 --debug
