#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
LLOCG Sim Tool (v2) — path-robust compile/sim

Key change vs v1:
- compile can omit --cost-yaml/--effect-yaml and will auto-find them under ROOT.
- ROOT is derived from --csv (parent directory).
- Default search base is ROOT/patterns if it exists, else ROOT.

Install:
  pip install pandas pyyaml

Usage (recommended):
  python3 llocg_sim_tool_v2.py compile \
    --csv llocg_db_out_full/cards_min_tokv1.csv \
    --out llocg_db_out_full/cards_compiled_v2.json

Optional overrides:
  --patterns-dir <dir>
  --cost-yaml <path>
  --effect-yaml <path>

Sim (placeholder):
  python3 llocg_sim_tool_v2.py sim \
    --compiled llocg_db_out_full/cards_compiled_v2.json \
    --runs 200 \
    --out llocg_db_out_full/sim_out_v2
"""
from __future__ import annotations

import argparse
import json
import random
import re
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
import yaml


def _auto_find_patterns(
    csv_path: Path,
    patterns_dir: Optional[Path],
    cost_yaml: Optional[Path],
    effect_yaml: Optional[Path],
) -> tuple[Path, Path]:
    """Auto-discover pattern YAMLs generated by upstream scripts."""
    root = csv_path.parent

    if patterns_dir is not None:
        base = patterns_dir
    else:
        cand = root / "patterns"
        base = cand if cand.exists() else root

    def pick_one(globs: List[str]) -> Optional[Path]:
        for g in globs:
            hits = sorted(base.glob(g))
            if hits:
                return hits[0]
        return None

    if cost_yaml is None:
        cost_yaml = pick_one(["cost_patterns*.yaml", "**/cost_patterns*.yaml"])
    if effect_yaml is None:
        effect_yaml = pick_one(["effect_patterns*.yaml", "**/effect_patterns*.yaml"])

    if cost_yaml is None:
        hits = sorted(root.glob("**/cost_patterns*.yaml"))
        cost_yaml = hits[0] if hits else None
    if effect_yaml is None:
        hits = sorted(root.glob("**/effect_patterns*.yaml"))
        effect_yaml = hits[0] if hits else None

    if cost_yaml is None:
        raise FileNotFoundError(f"cost_patterns*.yaml not found under: {root}")
    if effect_yaml is None:
        raise FileNotFoundError(f"effect_patterns*.yaml not found under: {root}")

    print(f"[INFO] ROOT        : {root}")
    print(f"[INFO] patterns dir: {base}")
    print(f"[INFO] cost yaml   : {cost_yaml}")
    print(f"[INFO] effect yaml : {effect_yaml}")
    return cost_yaml, effect_yaml


def _norm_brackets(t: str) -> str:
    if not isinstance(t, str):
        return ""
    return (
        t.replace("＜", "<").replace("＞", ">")
         .replace("〈", "<").replace("〉", ">")
         .replace("《", "<").replace("》", ">")
    )


def split_trigger_blocks(effect_text_norm: str) -> List[Dict[str, Any]]:
    t = _norm_brackets(effect_text_norm)
    lines = [ln.strip() for ln in t.splitlines() if ln.strip()]

    ability_headers = {"自動", "起動", "常時"}
    auto_triggers = {
        "登場時", "登場した時", "登場",
        "ライブ開始時", "ライブ成功時", "ライブ終了時", "ライブ中",
        "アタック時", "アタックした時",
        "ターン開始時", "ターン終了時",
    }
    known_conditions = {"センター", "ライト", "レフト"}
    turn_n_re = re.compile(r"^ターン\s*[0-9０-９]+\s*回$")
    eventish_re = re.compile(r"(開始時|成功時|終了時|した時|時$)")

    def classify_header(h: str) -> Tuple[str, str]:
        h = h.strip()
        if h in ability_headers:
            return ("ability", h)
        if h.startswith("自動"):
            return ("ability", "自動")
        if h.startswith("起動"):
            return ("ability", "起動")
        if h.startswith("常時"):
            return ("ability", "常時")
        if h in known_conditions or turn_n_re.match(h):
            return ("condition", h)
        if h in auto_triggers or eventish_re.search(h):
            return ("trigger", h)
        return ("condition", h)

    header_angle = re.compile(r"^<([^<>]+)>$")
    header_kakko = re.compile(r"^[\[\【\（]([^\]\】\）]+)[\]\】\）]$")

    def parse_header_line(ln: str) -> Optional[str]:
        m = header_angle.match(ln)
        if m and not ln.startswith("<("):
            return m.group(1).strip()
        m = header_kakko.match(ln)
        if m:
            return m.group(1).strip()
        return None

    blocks: List[Dict[str, Any]] = []
    cur_ability = "UNKNOWN"
    cur_trigger = "BODY"
    cur_conditions: List[str] = []
    cur_lines: List[str] = []

    def flush():
        nonlocal cur_lines
        if cur_lines:
            inferred = cur_ability
            if inferred == "UNKNOWN" and cur_trigger != "BODY":
                inferred = "自動"
            blocks.append({
                "ability_type": inferred,
                "trigger": cur_trigger,
                "conditions": list(cur_conditions),
                "text": "\n".join(cur_lines).strip(),
            })
        cur_lines = []

    for ln in lines:
        h = parse_header_line(ln)
        if h is not None:
            kind, val = classify_header(h)
            if kind == "ability":
                flush()
                cur_ability = val
                cur_trigger = "BODY"
                cur_conditions = []
                continue
            if kind == "trigger":
                flush()
                cur_ability = "自動"
                cur_trigger = val
                cur_conditions = []
                continue
            flush()
            cur_conditions.append(val)
            continue
        cur_lines.append(ln)

    flush()
    return blocks


def split_cost_effect_clauses(block_text: str) -> List[Dict[str, Any]]:
    if not isinstance(block_text, str) or not block_text.strip():
        return []
    raw_lines = [ln.strip() for ln in block_text.splitlines() if ln.strip()]

    def clean_leading_punct(s: str) -> str:
        return s.lstrip("、。,.，・ ").strip() if isinstance(s, str) else ""

    merge_tail = ("から", "を", "に", "へ", "の", "と", "して", "または", "および", "及び")
    merged: List[str] = []
    for ln in raw_lines:
        if not merged:
            merged.append(ln)
            continue
        prev = merged[-1]
        has_sep_prev = ("：" in prev) or (":" in prev)
        has_sep_ln = ("：" in ln) or (":" in ln)
        if (not has_sep_prev) and (not has_sep_ln) and any(prev.endswith(t) for t in merge_tail) and not ln.startswith("<"):
            merged[-1] = prev + ln
        else:
            merged.append(ln)

    clauses: List[Dict[str, Any]] = []
    for ln in merged:
        sep = "：" if "：" in ln else (":" if ":" in ln else None)
        if sep:
            left, right = ln.split(sep, 1)
            left, right = left.strip(), right.strip()
            optional = ("してもよい" in left) or ("してもよい" in ln)
            clauses.append({
                "optional": optional,
                "cost_text": clean_leading_punct(left),
                "effect_text": clean_leading_punct(right),
                "raw": ln,
            })
        else:
            clauses.append({
                "optional": ("してもよい" in ln),
                "cost_text": "",
                "effect_text": clean_leading_punct(ln),
                "raw": ln,
            })
    return clauses


@dataclass
class Pattern:
    id: str
    template: str
    op: str
    params: Dict[str, Any]
    note: str = ""
    confidence: float = 0.0


def load_patterns(yaml_path: Path) -> Dict[str, Pattern]:
    obj = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
    patterns: Dict[str, Pattern] = {}
    for p in obj.get("patterns", []):
        tmpl = str(p.get("template", "")).strip()
        if not tmpl:
            continue
        patterns[tmpl] = Pattern(
            id=str(p.get("id", "")),
            template=tmpl,
            op=str(p.get("op", "TODO")).strip(),
            params=p.get("params", {}) or {},
            note=str(p.get("note", "")),
            confidence=float(p.get("confidence", 0.0)),
        )
    return patterns


def compile_cards(csv_path: Path, cost_yaml: Path, effect_yaml: Path, out_json: Path) -> None:
    df = pd.read_csv(csv_path)
    for col in ["cardnumber", "cardname", "card_type_norm", "effect_text_norm"]:
        if col not in df.columns:
            raise SystemExit(f"[ERROR] required column missing: {col}")

    cost_pats = load_patterns(cost_yaml)
    eff_pats = load_patterns(effect_yaml)

    compiled: Dict[str, Any] = {"schema_version": 1, "source_csv": str(csv_path), "cards": []}

    for _, r in df.iterrows():
        cardno = str(r.get("cardnumber", "")).strip()
        name = str(r.get("cardname", "")).strip()
        ctype = str(r.get("card_type_norm", "")).strip()
        effect_text = str(r.get("effect_text_norm", "") or "")

        blocks = split_trigger_blocks(effect_text)
        abilities: List[Dict[str, Any]] = []

        for b in blocks:
            clauses = split_cost_effect_clauses(b.get("text", ""))
            conds = b.get("conditions", [])
            conds_s = ";".join([c for c in conds if isinstance(c, str) and c.strip()])

            compiled_clauses: List[Dict[str, Any]] = []
            for cl in clauses:
                cost_t = cl.get("cost_text", "").strip()
                eff_t = cl.get("effect_text", "").strip()
                cost_pat = cost_pats.get(cost_t) if cost_t else None
                eff_pat = eff_pats.get(eff_t) if eff_t else None

                compiled_clauses.append({
                    "optional": bool(cl.get("optional", False)),
                    "cost_template": cost_t,
                    "effect_template": eff_t,
                    "cost_op": asdict(cost_pat) if cost_pat else None,
                    "effect_op": asdict(eff_pat) if eff_pat else None,
                    "raw": cl.get("raw", ""),
                })

            abilities.append({
                "ability_type": b.get("ability_type", "UNKNOWN"),
                "trigger": b.get("trigger", "BODY"),
                "conditions": conds_s,
                "clauses": compiled_clauses,
            })

        compiled["cards"].append({
            "cardnumber": cardno,
            "cardname": name,
            "card_type": ctype,
            "abilities": abilities,
        })

    out_json.write_text(json.dumps(compiled, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[DONE] wrote {out_json}")


@dataclass
class GameState:
    deck: List[str]
    hand: List[str]
    waiting_room: List[str]


def _draw(state: GameState, n: int = 1):
    for _ in range(n):
        if not state.deck:
            break
        state.hand.append(state.deck.pop(0))


def _discard_from_hand(state: GameState, n: int = 1, rng: random.Random = random):
    for _ in range(n):
        if not state.hand:
            break
        idx = rng.randrange(len(state.hand))
        state.waiting_room.append(state.hand.pop(idx))


def run_min_sim(compiled_json: Path, runs: int, outdir: Path, seed: int = 1):
    obj = json.loads(compiled_json.read_text(encoding="utf-8"))
    cards = obj["cards"]
    rng = random.Random(seed)

    outdir.mkdir(parents=True, exist_ok=True)
    summary = []

    decklist = [c["cardnumber"] for c in cards]  # placeholder: 1 copy each

    for i in range(runs):
        deck = list(decklist)
        rng.shuffle(deck)
        state = GameState(deck=deck, hand=[], waiting_room=[])
        _draw(state, 5)

        for _turn in range(1, 6):
            _draw(state, 1)

            disc_n = 0
            for c in cards:
                for ab in c.get("abilities", []):
                    for cl in ab.get("clauses", []):
                        cop = cl.get("cost_op")
                        if cop and cop.get("op") == "discard_hand":
                            n = cop.get("params", {}).get("n", 1)
                            if isinstance(n, str):
                                m = re.search(r"\d+", n)
                                n = int(m.group(0)) if m else 1
                            disc_n = int(n)
                            break
                    if disc_n:
                        break
                if disc_n:
                    break
            if disc_n:
                _discard_from_hand(state, disc_n, rng)

        summary.append({
            "run": i,
            "deck_left": len(state.deck),
            "hand": len(state.hand),
            "waiting_room": len(state.waiting_room),
        })

    (outdir / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    pd.DataFrame(summary).to_csv(outdir / "summary.csv", index=False, encoding="utf-8-sig")
    print(f"[DONE] sim out -> {outdir}")


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    apc = sub.add_parser("compile", help="compile cards CSV + patterns into compiled JSON")
    apc.add_argument("--csv", required=True, type=Path)
    apc.add_argument("--out", required=True, type=Path)
    apc.add_argument("--patterns-dir", type=Path, default=None)
    apc.add_argument("--cost-yaml", type=Path, default=None)
    apc.add_argument("--effect-yaml", type=Path, default=None)

    aps = sub.add_parser("sim", help="run minimal simulation (placeholder)")
    aps.add_argument("--compiled", required=True, type=Path)
    aps.add_argument("--runs", type=int, default=100)
    aps.add_argument("--out", required=True, type=Path)
    aps.add_argument("--seed", type=int, default=1)

    args = ap.parse_args()

    if args.cmd == "compile":
        cost_yaml, effect_yaml = _auto_find_patterns(
            csv_path=args.csv,
            patterns_dir=args.patterns_dir,
            cost_yaml=args.cost_yaml,
            effect_yaml=args.effect_yaml,
        )
        compile_cards(args.csv, cost_yaml, effect_yaml, args.out)

    elif args.cmd == "sim":
        run_min_sim(args.compiled, args.runs, args.out, args.seed)


if __name__ == "__main__":
    main()
