"""Product catalogue helpers.

The canonical catalogue is generated by llocg_update_database.py from
product_release_registry.json. This module intentionally performs no network I/O.
"""
from __future__ import annotations
